[workspace]
authors = ["large chungus <>"]
channels = ["conda-forge"]
name = "example"
platforms = ["linux-64","osx-arm64","win-64"]
version = "0.1.0"

[tasks]
lab = "jupyter lab"
start = { depends-on = ["lab"], description = "start" }

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.2,<3"
notebook = ">=7.4.5,<8"
jupyterlab = ">=4.4.5,<5"
